### PR TITLE
Add [brackets] around the server IP address, needed for ipv6 addresses

### PR DESCRIPTION
**Pull request by corvus1**

### CODE REVIEW

**Review by mgorny — CHANGES_REQUESTED** [review]
This is going to break IPv4, isn't it? Better change it straight in ExternalIP class.

**Comment by corvus1** [comment]
That is above my paygrade. Could I maybe just check for ":" in the IP address and if there is one, it must be v6?

**Comment by mgorny** [comment]
I'll look at a proper solution later today.

**Comment by mgorny** [comment]
I'm sorry, could you help me reproduce this? FWICS pshs is set to bind to `0.0.0.0` by default, and I don't seem to be able to bind it to IPv6:

```
$ ./pshs -b '::' config.log
[warn] getaddrinfo: address family for nodename not supported
Unable to bind socket to :::16227
$ ./pshs -b '[::]' config.log
[warn] getaddrinfo: nodename nor servname provided, or not known
Unable to bind socket to [::]:18239
```

Could you tell me how you managed to make it work with IPv6?

**Comment by corvus1** [comment]
```
$ pshs -r 1234.png -b 2a02:2698:7006:1c55:1e1b:dff:feea:24a7
Ready to share 1 files.
Bound to 2a02:2698:7006:1c55:1e1b:dff:feea:24a7:24982.
Server reachable at: http://[2a02:2698:7006:1c55:1e1b:dff:feea:24a7]:24982/1234.png
```

You just have to be a bit more specific. :-D

**Comment by corvus1** [comment]
You can bind to ::1 but not to :: I assume it's because :: would include link-local addresses, but that's above my pay grade too.

**Comment by mgorny** [comment]
Well, I can't bind to `::1` either. Maybe I need to have a non-host IPv6 address first.

**Comment by corvus1** [comment]
I'm not sure. Do you even have ipv6 enabled and LL addresses assigned and such?

**Comment by mgorny** [comment]
I do have it enabled and I've just added a link-scope address. However, still no luck.

**Comment by corvus1** [comment]
Well, I dunno. But I can assure you it works for me. It binds to scope-global addresses or to ::1 and serves files to the clients. :-)

**Comment by mgorny** [comment]
Rebuilding libevent helped. I must've had broken headers at some point, I guess.

So I see that in your case the IPv6 address comes straight from `-b` option. I've implemented `IPAddrPrinter` class to abstract the logic away and made it print nice IPv6 addresses everywhere. After all, I've followed your suggestion of checking for `:`, that's definitely simpler then parsing it for valid IPv6 address every time.

**Comment by mgorny** [comment]
Now, I wonder if I can get IPv4+IPv6 bind working by default and not exploding on systems without IPv6.

**Comment by corvus1** [comment]
> After all, I've followed your suggestion of checking for `:`, that's definitely simpler then parsing it for valid IPv6 address every time.

That's a little bit ironic, but thanks for the software. :-) I forgot how many times I wanted something small to share a file with someone.

**Comment by mgorny** [comment]
Well, I thought it's getting the address from RTNL, and then it'd already know whether it's IPv6 or not. But I didn't think that you bind to it explicitly.

**Comment by corvus1** [comment]
I just built it from your repo and everything works quite happily. Plus now I know that you're supposed to use single quotes `'` for chars in C++ and not `"`. :-) Which is a nice bonus...

**Pull request closed without merging**
